### ISSUE TITLE
"leave course" button on Course page does not work

### ISSUE THREAD

**Issue by Leeciabarajas** [bradleypeterson/timetracker#34]
**Describe the bug**

**To Reproduce**
1. as new user go to courses
2. Select a course
3. click on " leave course"
4. agree to warning that proff will need to re-add you 
5. navigate back to page and see that you were never removed 

---> can never leave course ):

**Comment by jareddarnell** [comment]
The problem occurs due to there being no active column in the UserCourses table. 

To fix the problem would require adding an active column. It looks like everything else in the code is implemented to expect a column named isActive.

**Comment by jareddarnell** [comment]
The interface could also do with a way to see if a user is active within that course.

**Comment by jareddarnell** [comment]
Previous implementation deleted rows from the UserCourses table. The current solution I'm working on adds a row to UserCourses named isActive. This column is a boolean and determines if a user is part of that course.

The solution I'm working on looks like so:
![chrome_2020-07-15_21-22-09](https://user-images.githubusercontent.com/43456129/87622932-76207000-c6e1-11ea-8e65-f9f11061dbaa.png)
![devenv_2020-07-15_21-24-17](https://user-images.githubusercontent.com/43456129/87622971-8a646d00-c6e1-11ea-81ca-c999bd11be6e.png)
![devenv_2020-07-15_21-24-40](https://user-images.githubusercontent.com/43456129/87623000-98b28900-c6e1-11ea-9407-1eee87a6512f.png)

**Comment by jareddarnell** [comment]
Solve as of f355ed20f6190a3501fbe6913ea5b7674a5c4bda
