### ISSUE TITLE
Admin cannot create new course

### ISSUE THREAD

**Issue by matthewtingey1** [bradleypeterson/timetracker#37]
**Describe the bug**
As an admin I cannot create a new course in the system.

**To Reproduce**
1. Login as admin
2. Click on the courses tab
3. Try to click on the plus button to add a course
4. See exception thrown

**Expected behavior**
A new course should be added and you should see it in the list of courses on that page with no exception thrown.

**Comment by graceborges** [comment]
Already fixed
