### ISSUE TITLE
Deactivating a user does not work

### ISSUE THREAD

**Issue by chadrichins** [bradleypeterson/timetracker#40]
**Describe the bug**
Deactivating a user does not work

**To Reproduce**
1. Go to the user tab
2. Click on the active check mark to deselect the mark
3. You will get an error saying the following.
System.InvalidOperationException: 'The instance of entity type 'User' cannot be tracked because another instance with the same key value for {'userID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'
4. If you continue it seems like the user has been deleted but if you log out and then log back in the user is still marked as active.

**Expected behavior**
If you select the user to be inactive then the check mark should disappear and the user should not be able to log on.

**Comment by jareddarnell** [comment]
Issue tied to https://github.com/bradleypeterson/timetracker/issues/57

The problem is the ChangeUser function in UserService.cs

Proposed fix:
`       //Normal version doesn't save type or isActive
        public bool ChangeUser(User user)
        {
            var entry = _context.Users.First(u => u.userID == user.userID);

            _context.Entry(entry).CurrentValues.SetValues(user);
            _context.SaveChanges();
            return true;
        }`

**Comment by jareddarnell** [comment]
https://github.com/bradleypeterson/timetracker/issues/40 and https://github.com/bradleypeterson/timetracker/issues/57 should be resolved as of https://github.com/bradleypeterson/timetracker/commit/635589ddfe221f1979ee8921d584c5e3eea9733b
