### ISSUE TITLE
Exception thrown when trying to add a new start time in the first slot

### ISSUE THREAD

**Issue by TuckerBrady** [bradleypeterson/timetracker#46]
**Describe the bug**
When trying to backlog time, I am receiving multiple errors. One for changing just the start time to earlier than the current time, and one when changing the date to earlier than the current date.

Example: I forgot to add a time slot on my time card for work i put in yesterday. When I log in to add the slot, I am unable to finalize the update. I receive an error.

--OR--

I woke up early today to get in some work before my kids woke up, they woke up and we got going before i could log my time. When I try, later that same day, to add my time, I receive an error.

**To Reproduce**
1. Log in as admin
2. Click on the first available time slot
3. try to change the time/date to a previous time/date

**Expected behavior**
Should be able to add backlogged time to the time card. 

**Additional context**
When trying to add a start time on the current day that is prior to the current time, you receive the error: "Invalid start time: slot not created" in the browser, but the app keeps running.

When trying to add a start time on a previous day receive the error: "Failed to save time entry due to : negative time or clock out in the future."

**Comment by graceborges** [comment]
This bug has been fixed by another one
