### ISSUE TITLE
New Courses Don't Show Up on Dashboard

### ISSUE THREAD

**Issue by jareddarnell** [bradleypeterson/timetracker#51]
Courses other than the default do not show up on the dashboard.

**Comment by graceborges** [comment]
As of right now this is linked to why everything that is popping up on the dashboard is generic information. A lot bigger than originally expected

**Comment by jareddarnell** [comment]
Should be fixed as of https://github.com/bradleypeterson/timetracker/commit/7b57bfcec257f191dcd0dbde1497ae6d2dd5b179

<img align="left" src="https://i.imgur.com/PCR0hXh.png">
