### ISSUE TITLE
Admin can't change user type

### ISSUE THREAD

**Issue by TuckerBrady** [bradleypeterson/timetracker#57]
**Describe the bug**
Admin can't change the type for a user. When a new account is created, by default, it is a Student. When an admin tries to change the user type to Instructor or Admin, an error is thrown.

**To Reproduce**
1. Log in as admin
2. Click on the 'Users' tab at the top of the page to bring up the list of all users
3. Try changing a selected user's type
4. View error

**Comment by jareddarnell** [comment]
https://github.com/bradleypeterson/timetracker/issues/40 and https://github.com/bradleypeterson/timetracker/issues/57 should be resolved as of https://github.com/bradleypeterson/timetracker/commit/635589ddfe221f1979ee8921d584c5e3eea9733b
