### ISSUE TITLE
Hide Join Course button from Admin

### ISSUE THREAD

**Issue by matthewtingey1** [bradleypeterson/timetracker#58]
**Describe the bug**
Admin does not need the ability to join a course.

**To Reproduce**
1. Go to courses tab and select a course when signed in as admin.
2. You will see a join course button. (That should not be there)

**Expected behavior**
As an admin I should not see the join course button when I navigate to the courses page.

**Comment by jareddarnell** [comment]
Solved as of https://github.com/bradleypeterson/timetracker/pull/59
