### ISSUE TITLE
Start re-implementing Evals using EF Core

### ISSUE THREAD

**Issue by KaydenMiller** [bradleypeterson/timetracker#6]
The Evals system is not currently functioning. It needs to be updated to support EF Core, this means updating the DBHelper class as well as the HomeController to reflect these changes. 

We also need to look into any of the tables and relationships that need to be added to the DbContext.

**Comment by KaydenMiller** [comment]
This issue needs to be broken into several smaller issues as it is rather broad.

**Comment by KaydenMiller** [comment]
See the #29 for more information about this and how it may need to be implemented before starting work on it.

**Comment by JonathanGast** [comment]
The majority of the Eval System has been updated to support EF Core, but is currently commented out to keep the current system running. As Kayden posted, please see #29 as the scope has changed since the project was re-started at the first of the semester.
